function [E_WE,E_W,E_G,dE_dqa_G_3x3xnsxnqa,dE_dqe_G_3x3xnsxnqe,dE_dt_W] = get_E_group1(...
    ...
    st, ct,...
    st_ss,st_cs,st_sp,st_cp,...
    ct_ss,ct_cs,ct_sp,ct_cp,...
    ss_sp,ss_cp,cs_sp,cs_cp,...
    st_ss_sp,st_ss_cp,st_cs_sp,st_cs_cp,...
    ct_ss_sp,ct_ss_cp,ct_cs_sp,ct_cs_cp,...
    ...
    Rs_W_WE_tr,Rv_W_WE_tr,TD,nszrs,ns,...
    R_A_W,R_G_W,...
    ...
    dzeta_a_dt_tr,Ba_tr,yidx2,...
    ...
    dR_G_W_dqe_3x3x1xnqe,FLAG_free_free)

%st,ss,sp,ct,cs,cp,st_ss,st_cs,st_sp,st_cp,ct_ss,ct_cs,ct_sp,ct_cp,ss_sp,ss_cp,cs_sp,cs_cp,st_ss_sp,st_ss_cp,st_cs_sp,st_cs_cp,ct_ss_sp,ct_ss_cp,ct_cs_sp,ct_cs_cp

E_WE = static_method_groups.E_methods.get_E_WE(st,ct_ss,ct_cs,ct_sp,ct_cp,ss_sp,ss_cp,cs_sp,cs_cp,st_ss_sp,st_ss_cp,st_cs_sp,st_cs_cp);

E_W = static_method_groups.ct_methods.map_WEtoW(E_WE,Rs_W_WE_tr,Rv_W_WE_tr,TD);

E_G = static_method_groups.ct_methods.map_AtoG(E_W,R_G_W);

[dE_dt_W_91ns,dE_dqa_G_9qans] = static_method_groups.E_methods.get_dE(ct,st_ss,st_cs,st_sp,st_cp,ct_ss,ct_cs,ct_sp,ct_cp,ss_sp,ss_cp,cs_sp,cs_cp,st_ss_sp,st_ss_cp,st_cs_sp,st_cs_cp,ct_ss_sp,ct_ss_cp,ct_cs_sp,ct_cs_cp,nszrs,ns,Rs_W_WE_tr,Rv_W_WE_tr,R_G_W,TD,Ba_tr,dzeta_a_dt_tr,yidx2);
dE_dt_W = reshape(dE_dt_W_91ns,3,3,ns);
dE_dqa_G_3x3xnsxnqa = reshape(permute(dE_dqa_G_9qans,[1 4 3 2]),3,3,ns,[]);

if ~isempty(dR_G_W_dqe_3x3x1xnqe)
    dE_dqe_G_3x3xnsxnqe = utility_functions.MultiProd_(dR_G_W_dqe_3x3x1xnqe,E_W);
    %dE_dqe_G = reshape([dE_dqe(1:3,:,:),dE_dqe(4:6,:,:),dE_dqe(7:9,:,:)],9,3,ns);
    %             dE_dqe_G = [...
    %                 reshape(dE_dqe_G_3nq_3(:,1,:),3,[],ns) ;...
    %                 reshape(dE_dqe_G_3nq_3(:,2,:),3,[],ns) ;...
    %                 reshape(dE_dqe_G_3nq_3(:,3,:),3,[],ns)];
else
    dE_dqe_G_3x3xnsxnqe = zeros(3,3,ns,0);
end

%d2E_dzeta2_W = E_methods.get_d2E_dzeta2_W(st,nszrs,Rs_W_WE_tr,Rv_W_WE_tr,st_ss,st_cs,st_sp,st_cp,ct_ss,ct_cs,ct_sp,ct_cp,ss_sp,ss_cp,cs_sp,cs_cp,st_ss_sp,st_ss_cp,st_cs_sp,st_cs_cp,ct_ss_sp,ct_ss_cp,ct_cs_sp,ct_cs_cp,TD);


%         +=
%
%
%
%         d2varTheta_dt2_W_star = ...
%                 bsxfun(@times,dth_dt.*dsi_dt,dthdsiVec_W) +...
%                 bsxfun(@times,dph_dt,dey_dt_W);
%
%             d2varTheta_dt2_G_star = ...
%                 mult_Anm1_Bmpz(OmegaSkew_G,dvarTheta_dt_G)...
%                +ct_methods.map_WtoG(d2varTheta_dt2_W_star,R_G_W);
%
%             if ~FLAG_free_free
%                 d2varTheta_dt2_G_star = bsxfun(@plus,dOmega_dt_G,d2varTheta_dt2_G_star);
%             end
%
%

end